# Super-OS Post-Install Module
# Runs shell scripts after system is fully installed
---
script: "/root/super-os/scripts/calamares-postinstall.sh"

# Run in chroot
chroot: true

# Root required
chrootRoot: true
