# Systemd services to enable/disable in target system
---
services:
  enabled:
    - NetworkManager
    - sddm
    - libvirtd
    - bluetooth
  disabled:
    - sshd

targets:
  enabled:
    - graphical
  disabled: []

# Don't mask anything
mask: []
