# Welcome page (中文默认)
---
showSupportUrl: true
showKnownIssuesUrl: true
showReleaseNotesUrl: true

# 默认语言: 简体中文
locale: zh_CN
locale-global: zh_CN.UTF-8

# 国家选择
geoip:
    style: "json"
    url: "https://geoip.ubuntu.com/lookup"

requirements:
    requiredStorage: 32
    requiredRam: 8
    requiredCores: 4

    check:
        - storage
        - ram
        - power
        - internet
        - root
        - screen

    required:
        - storage
        - ram
        - root
