title   Super-OS Live (x86_64, UEFI)
linux   /%INSTALL_DIR%/boot/x86_64/vmlinuz-linux-zen
initrd  /%INSTALL_DIR%/boot/x86_64/initramfs-linux-zen.img
options archisobasedir=%INSTALL_DIR% archisolabel=%ARCHISO_LABEL% intel_iommu=on iommu=pt quiet console=ttyS0,115200 console=tty0
